# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: home_network.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12home_network.proto\x12\x0chome_network\"\x07\n\x05\x45mpty\"(\n\x04Host\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nip_address\x18\x02 \x01(\t\"L\n\x04Link\x12!\n\x05host1\x18\x01 \x01(\x0b\x32\x12.home_network.Host\x12!\n\x05host2\x18\x02 \x01(\x0b\x32\x12.home_network.Host\"P\n\x08Topology\x12!\n\x05hosts\x18\x01 \x03(\x0b\x32\x12.home_network.Host\x12!\n\x05links\x18\x02 \x03(\x0b\x32\x12.home_network.Link2\xa4\x02\n\x0bHomeNetwork\x12\x38\n\x0cStartNetwork\x12\x13.home_network.Empty\x1a\x13.home_network.Empty\x12\x37\n\x0bStopNetwork\x12\x13.home_network.Empty\x1a\x13.home_network.Empty\x12:\n\x0bGetTopology\x12\x13.home_network.Empty\x1a\x16.home_network.Topology\x12\x33\n\tAddDevice\x12\x12.home_network.Host\x1a\x12.home_network.Host\x12\x31\n\x07\x41\x64\x64Link\x12\x12.home_network.Link\x1a\x12.home_network.Linkb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'home_network_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_EMPTY']._serialized_start=36
  _globals['_EMPTY']._serialized_end=43
  _globals['_HOST']._serialized_start=45
  _globals['_HOST']._serialized_end=85
  _globals['_LINK']._serialized_start=87
  _globals['_LINK']._serialized_end=163
  _globals['_TOPOLOGY']._serialized_start=165
  _globals['_TOPOLOGY']._serialized_end=245
  _globals['_HOMENETWORK']._serialized_start=248
  _globals['_HOMENETWORK']._serialized_end=540
# @@protoc_insertion_point(module_scope)
